title: Visual Reactive Programming
description: A course on Visual Reactive Programming using Bonsai, developed by NeuroGEARS, Ltd.
funding: These course materials are part of the Cajal NeuroKit advanced neuroscience training programme.
funding_logo: cajal
funding_url: https://cajal-training.org/2022/bonsai1022/
google_analytics:
theme: minima
baseurl: "/vrp-2022"

twitter_username: bonsai_rx
github_username:  neurogears

kramdown:
  parse_block_html: true

plugins:
  - jekyll-seo-tag

include:
  - _pages
  - _slides

exclude:
  - Gemfile
  - Gemfile.lock
  - "**README.md"

header_pages:
  - _pages/neurokit.md
  - _pages/slides.md
  - _pages/worksheets.md

collections:
  # Ideally we would use collections for slides but this
  # breaks reveal.js markdown processing because of issue:
  # https://github.com/jekyll/jekyll/issues/6209
  # slides:
  #   output: true
  #   permalink: /:collection/:path/
  
  worksheets:
    output: true
    permalink: /:collection/:path/
